import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ReservationServiceService } from '../../services/reservation-service/reservation-service.service';
@Component({
  selector: 'app-reservations-list',
  templateUrl: './reservations-list.component.html',
  styleUrls: ['./reservations-list.component.css'],
})
export class ReservationsListComponent implements OnInit {

  username: String = "";

  reservations_list: any = []

  constructor(private route: ActivatedRoute, private service: ReservationServiceService) {
    this.service.getReservations().subscribe((reservations_list) => {
      console.log(reservations_list);
    });
  }

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.username = params['username'];
    });
  }

  reservations = [
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
    {
      key: 'facility1',
      date: 'dd/mm//yyyy',
      id_reserva: 'WE12345',
      firstName: 'Juan',
      lastName: 'Perez Oso',
      email: 'jperez@gmail.com',
      tarjeta: '***************2222',
      transaction: '123123123',
      dateStart: 'dd/mm//yyyy',
      dateEnd: 'dd/mm//yyyy',
      type: 'Standar',
    },
  ];
}
